import { Inter } from "next/font/google";
import Navbar from "./../../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en-US" }, { lang: "ar" }];
}

export default async function RootLayout({ children, params }) {
  
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
